/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ds.Cola;
import ds.ListaSimple;
import ds.Node;
import ds.Pila;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import models.Cita;
import models.GrupoDeRiesgo;
import models.Paciente;
import models.Vacuna;
import tableModels.CitasTableModel;
import tableModels.GruposDeRiesgoTableModel;
import tableModels.PacientesTableModel;
import tableModels.VacunasTableModel;

/**
 *
 * @author ez
 */
public class Principal extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private static Cola<Cita> colaDeCitas;
    private static Pila<GrupoDeRiesgo> pilaDeGruposDeRiesgo;
    private static ListaSimple<Vacuna> listaSimpleDeVacunas;
    private static ListaSimple<Paciente> listaSimpleDePacientes;
    private static ListaSimple<Paciente> listaSimpleDePacientesVacunados;
    
    private VacunasTableModel vacunaTableModel;
    private CitasTableModel citasTableModel;
    private GruposDeRiesgoTableModel gruposDeRiesgoTableModel;
    private PacientesTableModel pacientesTableModel;

    /**
     * Creates new form Main
     */
    public Principal() {
        initComponents();
        setSize(656,482);
        setTitle("Sistema De Vacunas");
        setLocationRelativeTo(null);
        setVisible(true);
        
        cardLayout = (CardLayout) pnlCards.getLayout();
        
        initDataStructures();
        
        ((JSpinner.DefaultEditor) inpDosis.getEditor()).getTextField().setEditable(false);
        calculateMetricts();
    }
    
    private void calculateMetricts() {
        int pacientesNoVacunados = 0;
        int pacientesVacunados = 0;
        int pacientesEsquemaCompleto = 0;
        
        Node<Paciente> paciente = listaSimpleDePacientes.getHead();
        while(paciente != null) {
            if (paciente.getData().getEsquemaCompleto()) {
                pacientesEsquemaCompleto++;
            } else if (paciente.getData().getFechaPrimeraDosis() != null) {
                pacientesVacunados++;
            } else {
                pacientesNoVacunados++;
            }
            paciente = paciente.getNext();
        }
        
        lblPacientesEsquemaCompleto.setText(pacientesEsquemaCompleto + "");
        lblPacientesVacunados.setText(pacientesVacunados + "");
        lblPacientesNoVacunados.setText(pacientesNoVacunados + "");
    }
    
    private void initDataStructures() {
        colaDeCitas = new Cola();
        pilaDeGruposDeRiesgo = new Pila();
        listaSimpleDeVacunas = new ListaSimple();
        listaSimpleDePacientes = new ListaSimple();
        listaSimpleDePacientesVacunados = new ListaSimple();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePane = new javax.swing.JPanel();
        btn_inicio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        grupoMenuPacientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_pacientes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        grupoMenuCitas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_citas = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        grupoMenuConfiguracion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_vacunas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_grupos_de_riesgo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_salir = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TitleBar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblMainTitle = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        cardInicio = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblPacientesNoVacunados = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblPacientesVacunados = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblPacientesEsquemaCompleto = new javax.swing.JLabel();
        cardPacientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        inpPacienteCedula = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        inpPacienteNombre = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        inpPacienteTelefono = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        cmbPacienteGrupoDeRiesgo = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        inpPacientePrimeraDosis = new com.toedter.calendar.JDateChooser();
        jLabel41 = new javax.swing.JLabel();
        inpPacienteSegundaDosis = new com.toedter.calendar.JDateChooser();
        jLabel40 = new javax.swing.JLabel();
        cmbPacienteVacuna = new javax.swing.JComboBox<>();
        chkPacienteEsquemaCompleto = new javax.swing.JCheckBox();
        btnAgregarNuevoPaciente = new javax.swing.JButton();
        cardCitas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        inpCitaCedula = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        inpCitaNombre = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        cmbCitaTipoVacuna = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        inpCitaFecha = new com.toedter.calendar.JDateChooser();
        btnCitaNueva = new javax.swing.JButton();
        cardVacunas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVacunas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        inpNombreVacuna = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        inpFarmaceutica = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        inpDosis = new javax.swing.JSpinner();
        btnAgregarVacuna = new javax.swing.JButton();
        cardGruposDeRiesgo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGruposDeRiesgo = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        inpGrpRiesgoNombre = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        inpGrpRiesgoDescripcion = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        inpGrpRiesgoEdadMin = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        inpGrpRiesgoEdadMax = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        inpGrpRiesgoEstado = new javax.swing.JComboBox<>();
        btnAgregarGrupoDeRiesgo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1280, 920));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 920));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 920));

        SidePane.setBackground(new java.awt.Color(106, 90, 205));
        SidePane.setPreferredSize(new java.awt.Dimension(300, 0));

        btn_inicio.setBackground(new java.awt.Color(72, 61, 139));
        btn_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inicio.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicioMousePressed(evt);
            }
        });
        btn_inicio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 0));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inicio");
        jLabel4.setPreferredSize(new java.awt.Dimension(230, 40));
        btn_inicio.add(jLabel4);

        SidePane.add(btn_inicio);

        grupoMenuPacientes.setBackground(new java.awt.Color(106, 90, 205));
        grupoMenuPacientes.setMinimumSize(new java.awt.Dimension(170, 39));
        grupoMenuPacientes.setPreferredSize(new java.awt.Dimension(250, 100));

        jLabel1.setForeground(new java.awt.Color(230, 230, 250));
        jLabel1.setText("Pascientes");
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 20));
        grupoMenuPacientes.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("");

        btn_pacientes.setBackground(new java.awt.Color(123, 104, 238));
        btn_pacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pacientes.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_pacientesMousePressed(evt);
            }
        });
        btn_pacientes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 0));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pacientes");
        jLabel7.setPreferredSize(new java.awt.Dimension(230, 40));
        btn_pacientes.add(jLabel7);

        grupoMenuPacientes.add(btn_pacientes);
        btn_pacientes.getAccessibleContext().setAccessibleName("");

        SidePane.add(grupoMenuPacientes);

        grupoMenuCitas.setBackground(new java.awt.Color(106, 90, 205));
        grupoMenuCitas.setMinimumSize(new java.awt.Dimension(170, 39));
        grupoMenuCitas.setPreferredSize(new java.awt.Dimension(250, 100));

        jLabel2.setForeground(new java.awt.Color(230, 230, 250));
        jLabel2.setText("Citas");
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 20));
        grupoMenuCitas.add(jLabel2);

        btn_citas.setBackground(new java.awt.Color(123, 104, 238));
        btn_citas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_citas.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_citas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_citasMousePressed(evt);
            }
        });
        btn_citas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 0));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Citas");
        jLabel9.setPreferredSize(new java.awt.Dimension(230, 40));
        btn_citas.add(jLabel9);

        grupoMenuCitas.add(btn_citas);

        SidePane.add(grupoMenuCitas);

        grupoMenuConfiguracion.setBackground(new java.awt.Color(106, 90, 205));
        grupoMenuConfiguracion.setMinimumSize(new java.awt.Dimension(170, 39));
        grupoMenuConfiguracion.setPreferredSize(new java.awt.Dimension(250, 120));

        jLabel3.setForeground(new java.awt.Color(230, 230, 250));
        jLabel3.setText("Configuración");
        jLabel3.setPreferredSize(new java.awt.Dimension(250, 20));
        grupoMenuConfiguracion.add(jLabel3);

        btn_vacunas.setBackground(new java.awt.Color(123, 104, 238));
        btn_vacunas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_vacunas.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_vacunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vacunasMousePressed(evt);
            }
        });
        btn_vacunas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 0));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vacunas");
        jLabel11.setPreferredSize(new java.awt.Dimension(230, 40));
        btn_vacunas.add(jLabel11);

        grupoMenuConfiguracion.add(btn_vacunas);

        btn_grupos_de_riesgo.setBackground(new java.awt.Color(123, 104, 238));
        btn_grupos_de_riesgo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_grupos_de_riesgo.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_grupos_de_riesgo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_grupos_de_riesgoMousePressed(evt);
            }
        });
        btn_grupos_de_riesgo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 0));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Grupos de Riesgo");
        jLabel10.setPreferredSize(new java.awt.Dimension(230, 40));
        btn_grupos_de_riesgo.add(jLabel10);

        grupoMenuConfiguracion.add(btn_grupos_de_riesgo);

        SidePane.add(grupoMenuConfiguracion);

        jSeparator2.setPreferredSize(new java.awt.Dimension(240, 10));
        SidePane.add(jSeparator2);

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_salirMousePressed(evt);
            }
        });
        btn_salir.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(72, 61, 139));
        jLabel5.setText("Salir");
        jLabel5.setPreferredSize(new java.awt.Dimension(230, 40));
        btn_salir.add(jLabel5);

        SidePane.add(btn_salir);

        getContentPane().add(SidePane, java.awt.BorderLayout.WEST);

        TitleBar.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(316, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/covid-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMainTitle.setBackground(new java.awt.Color(72, 61, 139));
        lblMainTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblMainTitle.setForeground(new java.awt.Color(72, 61, 139));
        lblMainTitle.setText("Inicio");
        lblMainTitle.setPreferredSize(new java.awt.Dimension(230, 40));

        javax.swing.GroupLayout TitleBarLayout = new javax.swing.GroupLayout(TitleBar);
        TitleBar.setLayout(TitleBarLayout);
        TitleBarLayout.setHorizontalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(781, Short.MAX_VALUE))
        );
        TitleBarLayout.setVerticalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleBarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createSequentialGroup()
                        .addComponent(lblMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(TitleBar, java.awt.BorderLayout.NORTH);

        pnlCards.setBackground(new java.awt.Color(186, 228, 248));
        pnlCards.setPreferredSize(new java.awt.Dimension(980, 914));
        pnlCards.setLayout(new java.awt.CardLayout());

        cardInicio.setBackground(new java.awt.Color(240, 248, 255));

        jPanel10.setBackground(new java.awt.Color(29, 61, 89));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel10.setPreferredSize(new java.awt.Dimension(240, 100));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pacientes No Vacunados");

        lblPacientesNoVacunados.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblPacientesNoVacunados.setForeground(new java.awt.Color(255, 255, 255));
        lblPacientesNoVacunados.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPacientesNoVacunados)
                    .addComponent(jLabel6))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPacientesNoVacunados, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cardInicio.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(29, 61, 89));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel11.setPreferredSize(new java.awt.Dimension(240, 100));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pacientes Vacunados");

        lblPacientesVacunados.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblPacientesVacunados.setForeground(new java.awt.Color(255, 255, 255));
        lblPacientesVacunados.setText("0");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPacientesVacunados)
                    .addComponent(jLabel12))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPacientesVacunados, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cardInicio.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(29, 61, 89));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel12.setPreferredSize(new java.awt.Dimension(240, 100));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pacientes Esquema Completo");

        lblPacientesEsquemaCompleto.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblPacientesEsquemaCompleto.setForeground(new java.awt.Color(255, 255, 255));
        lblPacientesEsquemaCompleto.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPacientesEsquemaCompleto)
                    .addComponent(jLabel15))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPacientesEsquemaCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cardInicio.add(jPanel12);

        pnlCards.add(cardInicio, "cardInicio");

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPacientes);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setText("Nuevo Paciente");

        jLabel27.setText("Cédula:");
        jLabel27.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel7.add(jLabel27);

        inpPacienteCedula.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel7.add(inpPacienteCedula);

        jLabel28.setText("Nombre:");
        jLabel28.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel7.add(jLabel28);

        inpPacienteNombre.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel7.add(inpPacienteNombre);

        jLabel37.setText("Teléfono:");
        jLabel37.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel7.add(jLabel37);

        inpPacienteTelefono.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel7.add(inpPacienteTelefono);

        jLabel38.setText("Grupo De Riesgo");
        jLabel38.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel7.add(jLabel38);

        cmbPacienteGrupoDeRiesgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupo De Riesgo 1", "Grupo De Riesgo 2", "Grupo De Riesgo 3", "Grupo De Riesgo 4", "Grupo De Riesgo 5" }));
        cmbPacienteGrupoDeRiesgo.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel7.add(cmbPacienteGrupoDeRiesgo);

        jLabel39.setText("Fecha Primera Dosis:");
        jLabel39.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel7.add(jLabel39);

        inpPacientePrimeraDosis.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel7.add(inpPacientePrimeraDosis);

        jLabel41.setText("Fecha Segunda Dosis:");
        jLabel41.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel7.add(jLabel41);

        inpPacienteSegundaDosis.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel7.add(inpPacienteSegundaDosis);

        jLabel40.setText("Vacuna:");
        jLabel40.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel7.add(jLabel40);

        cmbPacienteVacuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer", "Jhonson&Jhonson", "Moderna" }));
        cmbPacienteVacuna.setPreferredSize(new java.awt.Dimension(220, 40));
        cmbPacienteVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPacienteVacunaActionPerformed(evt);
            }
        });
        jPanel7.add(cmbPacienteVacuna);

        chkPacienteEsquemaCompleto.setText("Esquema Completo");
        chkPacienteEsquemaCompleto.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel7.add(chkPacienteEsquemaCompleto);

        btnAgregarNuevoPaciente.setText("Nuevo Paciente");
        btnAgregarNuevoPaciente.setPreferredSize(new java.awt.Dimension(220, 40));
        btnAgregarNuevoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarNuevoPacienteMousePressed(evt);
            }
        });
        jPanel7.add(btnAgregarNuevoPaciente);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 251, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardPacientesLayout = new javax.swing.GroupLayout(cardPacientes);
        cardPacientes.setLayout(cardPacientesLayout);
        cardPacientesLayout.setHorizontalGroup(
            cardPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardPacientesLayout.setVerticalGroup(
            cardPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCards.add(cardPacientes, "cardPacientes");

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCitas);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("Nueva Cita");

        jLabel23.setText("Cédula:");
        jLabel23.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel5.add(jLabel23);

        inpCitaCedula.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel5.add(inpCitaCedula);

        jLabel24.setText("Nombre:");
        jLabel24.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel5.add(jLabel24);

        inpCitaNombre.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel5.add(inpCitaNombre);

        jLabel36.setText("Vacuna:");
        jLabel36.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel5.add(jLabel36);

        cmbCitaTipoVacuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer", "Jhonson&Jhonson", "Moderna" }));
        cmbCitaTipoVacuna.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel5.add(cmbCitaTipoVacuna);

        jLabel25.setText("Fecha de Cita:");
        jLabel25.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel5.add(jLabel25);

        inpCitaFecha.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel5.add(inpCitaFecha);

        btnCitaNueva.setText("Nueva Cita");
        btnCitaNueva.setPreferredSize(new java.awt.Dimension(220, 40));
        btnCitaNueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCitaNuevaMousePressed(evt);
            }
        });
        jPanel5.add(btnCitaNueva);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 279, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardCitasLayout = new javax.swing.GroupLayout(cardCitas);
        cardCitas.setLayout(cardCitasLayout);
        cardCitasLayout.setHorizontalGroup(
            cardCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardCitasLayout.setVerticalGroup(
            cardCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCards.add(cardCitas, "cardCitas");

        cardVacunas.setBackground(new java.awt.Color(240, 248, 255));

        tblVacunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVacunas);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setText("Nueva Vacuna");

        jLabel13.setText("Nombre:");
        jLabel13.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel3.add(jLabel13);

        inpNombreVacuna.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel3.add(inpNombreVacuna);

        jLabel20.setText("Farmaceutica");
        jLabel20.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel3.add(jLabel20);

        inpFarmaceutica.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel3.add(inpFarmaceutica);

        jLabel21.setText("Número Dosis");
        jLabel21.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel3.add(jLabel21);

        inpDosis.setEditor(new javax.swing.JSpinner.NumberEditor(inpDosis, ""));
        inpDosis.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel3.add(inpDosis);

        btnAgregarVacuna.setText("Agregar Vacuna");
        btnAgregarVacuna.setPreferredSize(new java.awt.Dimension(220, 40));
        btnAgregarVacuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarVacunaMousePressed(evt);
            }
        });
        jPanel3.add(btnAgregarVacuna);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 275, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout cardVacunasLayout = new javax.swing.GroupLayout(cardVacunas);
        cardVacunas.setLayout(cardVacunasLayout);
        cardVacunasLayout.setHorizontalGroup(
            cardVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardVacunasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardVacunasLayout.setVerticalGroup(
            cardVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardVacunasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCards.add(cardVacunas, "cardVacunas");

        tblGruposDeRiesgo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblGruposDeRiesgo);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setText("Nuevo Grupo De Riesgo");

        jLabel31.setText("Nombre:");
        jLabel31.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel9.add(jLabel31);

        inpGrpRiesgoNombre.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel9.add(inpGrpRiesgoNombre);

        jLabel32.setText("Descripción:");
        jLabel32.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel9.add(jLabel32);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setPreferredSize(new java.awt.Dimension(220, 88));

        inpGrpRiesgoDescripcion.setColumns(20);
        inpGrpRiesgoDescripcion.setRows(5);
        inpGrpRiesgoDescripcion.setPreferredSize(new java.awt.Dimension(220, 80));
        inpGrpRiesgoDescripcion.setSize(new java.awt.Dimension(220, 80));
        jScrollPane5.setViewportView(inpGrpRiesgoDescripcion);

        jPanel9.add(jScrollPane5);

        jLabel33.setText("Edad Minima:");
        jLabel33.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel9.add(jLabel33);

        inpGrpRiesgoEdadMin.setEditor(new javax.swing.JSpinner.NumberEditor(inpGrpRiesgoEdadMin, ""));
        inpGrpRiesgoEdadMin.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel9.add(inpGrpRiesgoEdadMin);

        jLabel34.setText("Edad Máxima:");
        jLabel34.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel9.add(jLabel34);

        inpGrpRiesgoEdadMax.setEditor(new javax.swing.JSpinner.NumberEditor(inpGrpRiesgoEdadMax, ""));
        inpGrpRiesgoEdadMax.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel9.add(inpGrpRiesgoEdadMax);

        jLabel35.setText("Estado:");
        jLabel35.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel9.add(jLabel35);

        inpGrpRiesgoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Progreso", "Completado" }));
        inpGrpRiesgoEstado.setPreferredSize(new java.awt.Dimension(220, 40));
        jPanel9.add(inpGrpRiesgoEstado);

        btnAgregarGrupoDeRiesgo.setText("Agregar Grupo de Riesgo");
        btnAgregarGrupoDeRiesgo.setPreferredSize(new java.awt.Dimension(220, 40));
        btnAgregarGrupoDeRiesgo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarGrupoDeRiesgoMousePressed(evt);
            }
        });
        jPanel9.add(btnAgregarGrupoDeRiesgo);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardGruposDeRiesgoLayout = new javax.swing.GroupLayout(cardGruposDeRiesgo);
        cardGruposDeRiesgo.setLayout(cardGruposDeRiesgoLayout);
        cardGruposDeRiesgoLayout.setHorizontalGroup(
            cardGruposDeRiesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGruposDeRiesgoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardGruposDeRiesgoLayout.setVerticalGroup(
            cardGruposDeRiesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGruposDeRiesgoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardGruposDeRiesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(366, Short.MAX_VALUE))
        );

        pnlCards.add(cardGruposDeRiesgo, "cardGruposDeRiesgo");

        getContentPane().add(pnlCards, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMousePressed
        System.exit(0);
    }//GEN-LAST:event_btn_salirMousePressed

    private void btn_inicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMousePressed
        resetAllMenuItemsColor();
        setMenuActiveColor(btn_inicio);
        lblMainTitle.setText("Inicio");
        switchCardContent("cardInicio");
        calculateMetricts();
    }//GEN-LAST:event_btn_inicioMousePressed

    private void btn_citasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_citasMousePressed
        resetAllMenuItemsColor();
        setMenuActiveColor(btn_citas);
        lblMainTitle.setText("Citas");
        
        citasTableModel = new CitasTableModel(colaDeCitas);
        tblCitas.setModel(citasTableModel);
        
        switchCardContent("cardCitas");
    }//GEN-LAST:event_btn_citasMousePressed

    private void btn_vacunasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vacunasMousePressed
        resetAllMenuItemsColor();
        setMenuActiveColor(btn_vacunas);
        lblMainTitle.setText("Vacunas");
        
        vacunaTableModel = new VacunasTableModel(listaSimpleDeVacunas);
        tblVacunas.setModel(vacunaTableModel);
        
        switchCardContent("cardVacunas");
    }//GEN-LAST:event_btn_vacunasMousePressed

    private void btn_grupos_de_riesgoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_grupos_de_riesgoMousePressed
        resetAllMenuItemsColor();
        setMenuActiveColor(btn_grupos_de_riesgo);
        lblMainTitle.setText("Grupos de Riesgo");
        
        gruposDeRiesgoTableModel = new GruposDeRiesgoTableModel(pilaDeGruposDeRiesgo);
        tblGruposDeRiesgo.setModel(gruposDeRiesgoTableModel);
        
        switchCardContent("cardGruposDeRiesgo");
    }//GEN-LAST:event_btn_grupos_de_riesgoMousePressed

    private void btn_pacientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pacientesMousePressed
        resetAllMenuItemsColor();
        setMenuActiveColor(btn_pacientes);
        lblMainTitle.setText("Pacientes");
        
        pacientesTableModel = new PacientesTableModel(listaSimpleDePacientes);
        tblPacientes.setModel(pacientesTableModel);
        
        switchCardContent("cardPacientes");
    }//GEN-LAST:event_btn_pacientesMousePressed

    private void btnAgregarVacunaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarVacunaMousePressed
        Vacuna nuevaVacuna = new Vacuna(inpFarmaceutica.getText(), inpNombreVacuna.getText(), (Integer) inpDosis.getValue());
        listaSimpleDeVacunas.push(nuevaVacuna);
        vacunaTableModel.fireTableDataChanged();
        
        inpFarmaceutica.setText(null);
        inpNombreVacuna.setText(null);
        inpDosis.setValue(0);
    }//GEN-LAST:event_btnAgregarVacunaMousePressed

    private void btnCitaNuevaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaNuevaMousePressed
        Cita cita = new Cita();
        cita.setCedulaPaciente(inpCitaCedula.getText());
        cita.setNombrePaciente(inpCitaNombre.getText());
        cita.setTipoDeVacuna((String) cmbCitaTipoVacuna.getSelectedItem());
        Date fecha = inpCitaFecha.getDate();
        cita.setFechaDeCita(DateFormat.getDateInstance().format(fecha));
        
        System.out.println(cita);
        
        colaDeCitas.enqueue(cita);
        System.out.println(colaDeCitas);
        citasTableModel.fireTableDataChanged();
        
        inpCitaCedula.setText(null);
        inpCitaNombre.setText(null);
        cmbCitaTipoVacuna.setSelectedItem(null);
        inpCitaFecha.setDate(null);
    }//GEN-LAST:event_btnCitaNuevaMousePressed

    private void btnAgregarNuevoPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarNuevoPacienteMousePressed
        Paciente nuevoPaciente = new Paciente();
        
        nuevoPaciente.setCedula(inpPacienteCedula.getText());
        nuevoPaciente.setNombreCompleto(inpPacienteNombre.getText());
        nuevoPaciente.setTelefono(inpPacienteTelefono.getText());
        nuevoPaciente.setGrupoDeRiesgo((String) cmbPacienteGrupoDeRiesgo.getSelectedItem());
        
        Date primeraDosis = inpPacientePrimeraDosis.getDate();
        Date segundaDosis = inpPacienteSegundaDosis.getDate();
        
        if (primeraDosis != null) {
           nuevoPaciente.setFechaPrimeraDosis(DateFormat.getDateInstance().format(primeraDosis));
        }
        if (segundaDosis != null) {
            nuevoPaciente.setFechaSegundaDosis(DateFormat.getDateInstance().format(segundaDosis));
        }
        
        nuevoPaciente.setTipoVacuna((String) cmbPacienteVacuna.getSelectedItem());
        nuevoPaciente.setEsquemaCompleto(chkPacienteEsquemaCompleto.isSelected());
        
        listaSimpleDePacientes.push(nuevoPaciente);
        pacientesTableModel.fireTableDataChanged();
        
        inpPacienteCedula.setText(null);
        inpPacienteNombre.setText(null);
        inpPacienteTelefono.setText(null);
        cmbPacienteGrupoDeRiesgo.setSelectedItem(null);
        
        inpPacientePrimeraDosis.setDate(null);
        inpPacienteSegundaDosis.setDate(null);
        
        cmbPacienteVacuna.setSelectedItem(null);
        chkPacienteEsquemaCompleto.setSelected(false);
    }//GEN-LAST:event_btnAgregarNuevoPacienteMousePressed

    private void btnAgregarGrupoDeRiesgoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarGrupoDeRiesgoMousePressed
        GrupoDeRiesgo gr = new GrupoDeRiesgo();
        gr.setNombre(inpGrpRiesgoNombre.getText());
        gr.setDescripcion(inpGrpRiesgoDescripcion.getText());
        gr.setEdadMinima((Integer) inpGrpRiesgoEdadMin.getValue());
        gr.setEdadMaxima((Integer) inpGrpRiesgoEdadMax.getValue());
        gr.setEstado((String) inpGrpRiesgoEstado.getSelectedItem());
        
        pilaDeGruposDeRiesgo.push(gr);
        gruposDeRiesgoTableModel.fireTableDataChanged();
        
        inpGrpRiesgoNombre.setText(null);
        inpGrpRiesgoDescripcion.setText(null);
        inpGrpRiesgoEdadMin.setValue(0);
        inpGrpRiesgoEdadMax.setValue(0);
        inpGrpRiesgoEstado.setSelectedItem(null);
    }//GEN-LAST:event_btnAgregarGrupoDeRiesgoMousePressed

    private void cmbPacienteVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPacienteVacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPacienteVacunaActionPerformed

    private void setMenuActiveColor(JPanel panel) {
        panel.setBackground(new Color(72,61,139));
    }
    
    private void resetAllMenuItemsColor() {
        resetActiveMenuColor(btn_inicio);
        resetActiveMenuColor(btn_pacientes);
        resetActiveMenuColor(btn_citas);
        resetActiveMenuColor(btn_vacunas);
        resetActiveMenuColor(btn_grupos_de_riesgo);
    }
    
    private void resetActiveMenuColor(JPanel panel) {
        panel.setBackground(new Color(123,104,238));
    }
    
    private void switchCardContent(String cardName) {
        cardLayout.show(pnlCards, cardName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidePane;
    private javax.swing.JPanel TitleBar;
    private javax.swing.JButton btnAgregarGrupoDeRiesgo;
    private javax.swing.JButton btnAgregarNuevoPaciente;
    private javax.swing.JButton btnAgregarVacuna;
    private javax.swing.JButton btnCitaNueva;
    private javax.swing.JPanel btn_citas;
    private javax.swing.JPanel btn_grupos_de_riesgo;
    private javax.swing.JPanel btn_inicio;
    private javax.swing.JPanel btn_pacientes;
    private javax.swing.JPanel btn_salir;
    private javax.swing.JPanel btn_vacunas;
    private javax.swing.JPanel cardCitas;
    private javax.swing.JPanel cardGruposDeRiesgo;
    private javax.swing.JPanel cardInicio;
    private javax.swing.JPanel cardPacientes;
    private javax.swing.JPanel cardVacunas;
    private javax.swing.JCheckBox chkPacienteEsquemaCompleto;
    private javax.swing.JComboBox<String> cmbCitaTipoVacuna;
    private javax.swing.JComboBox<String> cmbPacienteGrupoDeRiesgo;
    private javax.swing.JComboBox<String> cmbPacienteVacuna;
    private javax.swing.JPanel grupoMenuCitas;
    private javax.swing.JPanel grupoMenuConfiguracion;
    private javax.swing.JPanel grupoMenuPacientes;
    private javax.swing.JTextField inpCitaCedula;
    private com.toedter.calendar.JDateChooser inpCitaFecha;
    private javax.swing.JTextField inpCitaNombre;
    private javax.swing.JSpinner inpDosis;
    private javax.swing.JTextField inpFarmaceutica;
    private javax.swing.JTextArea inpGrpRiesgoDescripcion;
    private javax.swing.JSpinner inpGrpRiesgoEdadMax;
    private javax.swing.JSpinner inpGrpRiesgoEdadMin;
    private javax.swing.JComboBox<String> inpGrpRiesgoEstado;
    private javax.swing.JTextField inpGrpRiesgoNombre;
    private javax.swing.JTextField inpNombreVacuna;
    private javax.swing.JTextField inpPacienteCedula;
    private javax.swing.JTextField inpPacienteNombre;
    private com.toedter.calendar.JDateChooser inpPacientePrimeraDosis;
    private com.toedter.calendar.JDateChooser inpPacienteSegundaDosis;
    private javax.swing.JTextField inpPacienteTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblPacientesEsquemaCompleto;
    private javax.swing.JLabel lblPacientesNoVacunados;
    private javax.swing.JLabel lblPacientesVacunados;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JTable tblCitas;
    private javax.swing.JTable tblGruposDeRiesgo;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTable tblVacunas;
    // End of variables declaration//GEN-END:variables
}
